# Generated by Django 4.2.6 on 2023-11-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="title",
            field=models.CharField(max_length=150),
        ),
    ]
