# Generated by Django 4.2.6 on 2023-11-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0003_recipe_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="recipe",
            name="slug",
            field=models.SlugField(unique=True),
        ),
        migrations.AddField(
            model_name="recipe",
            name="category",
            field=models.ManyToManyField(related_name="recipes", to="recipes.category"),
        ),
    ]
