# Generated by Django 4.2.6 on 2024-01-12 10:41

import django.core.validators
from django.db import migrations, models
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_category_options_alter_recipe_full_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="preview_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.base.services.recipe_preview_path,
                validators=[
                    src.base.services.validate_avatar_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                ],
            ),
        ),
    ]
