# Generated by Django 4.2.6 on 2024-02-22 13:51

from django.db import migrations, models
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0004_remove_ingredient_units_and_more"),
        (
            "taggit",
            "0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx",
        ),
        ("recipes", "0008_recipe_preview_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="recipe",
            options={"verbose_name": "Recipe", "verbose_name_plural": "Recipes"},
        ),
        migrations.AddField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="ingredients.ingredientinrecipe"
            ),
        ),
        migrations.AddField(
            model_name="recipe",
            name="is_repost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="recipe",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="tag",
            field=taggit.managers.TaggableManager(
                blank=True,
                help_text="A comma-separated list of tags.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
        migrations.AlterIndexTogether(
            name="recipe",
            index_together={("title", "slug")},
        ),
    ]
