# Generated by Django 4.2.6 on 2024-11-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
