# Generated by Django 5.0.5 on 2024-05-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0011_alter_recipe_cooking_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="published",
            field=models.BooleanField(default=False),
        ),
    ]
