# Generated by Django 4.2.6 on 2025-02-23 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0012_recipe_published"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="original_recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reposts",
                to="recipes.recipe",
            ),
        ),
    ]
