# Generated by Django 4.2.6 on 2025-03-10 08:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingredients", "0004_remove_ingredient_units_and_more"),
        ("recipes", "0013_recipe_original_recipe"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="recipe",
            new_name="recipes_rec_title_c495fd_idx",
            old_fields=("title", "slug"),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="category",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="recipes.category"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="cooking_time",
            field=models.PositiveIntegerField(
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(1440),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="ingredients",
            field=models.ManyToManyField(
                blank=True, related_name="recipes", to="ingredients.ingredientinrecipe"
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="published",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name="recipe",
            index=models.Index(
                fields=["published", "pub_date"], name="recipes_rec_publish_1d70be_idx"
            ),
        ),
    ]
