# Generated by Django 4.2.6 on 2024-03-07 22:31

import django.core.validators
from django.db import migrations, models
import phonenumber_field.modelfields
import src.base.services


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["-date_joined"],
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterModelManagers(
            name="customuser",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="join_date",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="second_name",
        ),
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True, max_length=128, null=True, region=None
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=src.base.services.user_avatar_path,
                validators=[
                    src.base.services.validate_avatar_size,
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    ),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="city",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Zа-яА-Я\\s\\-\\‘\\u00C0-\\u017F]+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="country",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Zа-яА-Я\\s\\-\\‘\\u00C0-\\u017F]+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="first_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Zа-яА-Я\\s\\-\\‘\\u00C0-\\u017F]+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="last_name",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=30,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-zA-Zа-яА-Я\\s\\-\\‘\\u00C0-\\u017F]+$"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
