# Generated by Django 4.2.6 on 2024-02-22 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_remove_customuser_second_name_customuser_phone_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="display_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
