# Generated by Django 4.2.6 on 2025-03-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_customuser_options_alter_customuser_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=150, null=True, unique=True),
        ),
    ]
