# Generated by Django 4.2.6 on 2024-02-22 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0008_recipe_preview_image"),
        ("ingredients", "0003_alter_ingredient_name_alter_unit_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="units",
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="ingredient",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingredientsinrecipe",
                to="ingredients.ingredient",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ingredientsinrecipe",
                to="recipes.recipe",
            ),
        ),
        migrations.AlterField(
            model_name="ingredientinrecipe",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="ingredientsinrecipe",
                to="ingredients.unit",
            ),
        ),
    ]
