# Generated by Django 4.2.6 on 2023-12-05 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("recipes", "0003_recipe_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="ViewRecipes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        db_index=True, max_length=255, verbose_name="Пользователь"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Время просмотра"
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="views",
                        to="recipes.recipe",
                        verbose_name="Рецепт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Просмотр рецепта",
                "verbose_name_plural": "Просмотры рецептов",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="viewrecipes",
            constraint=models.UniqueConstraint(
                fields=("user", "recipe"), name="unique_view"
            ),
        ),
    ]
