# Generated by Django 4.2.6 on 2023-12-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="viewrecipes",
            name="count",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Количество просмотров"
            ),
        ),
    ]
