# Generated by Django 4.2.6 on 2024-02-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("view", "0003_remove_viewrecipes_count"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="viewrecipes",
            name="unique_view",
        ),
    ]
