# Generated by Django 4.2.6 on 2023-12-16 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0005_alter_recipe_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("favorite", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="favorite",
            name="recipe",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="recipes.recipe"
            ),
        ),
    ]
