name: Build and Backend
on:
  push:
    branches: ["devops-docker-files"]
  pull_request:
    branches: ["devops-docker-files"]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .docker/Dockerfile
          push: true
          tags: sousvidzen/backend:dev
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          script: |
            # Log in to Docker Hub
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            # Create necessary directories and docker-compose file
            mkdir -p ~/sous && cd ~/sous
            cat << 'EOF' > docker-compose.yml
            version: "3.8"

            services:
              backend:
                image: sousvidzen/backend:dev
                container_name: sous-vid-zen-backend
                expose:
                  - "8000"
                environment:
                  - NODE_ENV=production
                restart: unless-stopped
                networks:
                  - sous-vid-zen-network

              nginx:
                image: nginx:latest
                container_name: sous-vid-zen-nginx
                ports:
                  - "80:80"
                volumes:
                  - ./nginx.conf:/etc/nginx/nginx.conf:ro
                depends_on:
                  - backend
                restart: unless-stopped
                networks:
                  - sous-vid-zen-network

            networks:
              sous-vid-zen-network:
                driver: bridge

    
            # Pull the latest image and start the container
            docker-compose pull
            docker-compose up -d

            # Log out of Docker Hub
            docker logout
